;;; -*- Mode:Lisp;Package:NETWORK-INTERNALS;Base:10-*-
;;; (c) 1984 Massachusetts Institute of Technology
;;;
;;; This is SYS: NETWORK; SYMBOLS LISP
;;;
;;; This is a list of the NET: symbols.  All other network-type symbols will be in NETI:
;;; Brand S namespace-related symbols ARE NOT defined in here

(DEFCONST INITIAL-NETWORK-SYMBOLS '(

 *LOCAL-HOST* 
 *LOCAL-SITE*
 
 ABORT-SERVICE-ACCESS-PATH-FUTURE
 CONTINUE-SERVICE-ACCESS-PATH-FUTURE
 DEFINE-MEDIUM
 DEFINE-PROTOCOL
 DEFINE-SERVER
 FIND-PATH-TO-PROTOCOL-ON-HOST
 FIND-PATHS-TO-PROTOCOL-ON-HOST
 FIND-PATHS-TO-SERVICE
 FIND-PATHS-TO-SERVICE-ON-HOST
 GET-CONNECTION-FOR-SERVICE
 INVOKE-MULTIPLE-SERVICES
 INVOKE-SERVICE-ON-HOST
 INVOKE-SERVICE-ACCESS-PATH
 NETWORK
 NETWORK-TYPE-FLAVOR
 NOTE-SERVER-CLOSED
 NOTE-SERVER-ESTABLISHED
 SERVICE-ACCESS-PATH-FUTURE-CONNECTED-P
 START-SERVICE-ACCESS-PATH-FUTURE

))