;;; -*- Mode: LISP; Package: CHAOS; Base: 8; Readtable:T -*-
;;; *** THIS FILE WAS AUTOMATICALLY GENERATED BY A PROGRAM, DO NOT EDIT IT ***
;;; Host table made from OZ: /site/hosts.text
;;; Written 16-Sep-26 02:22:49 by LISPM,
;;; while running on Lisp Machine One from band 9
;;; with Experimental System 1000.0, Experimental ZWEI 130.0, microcode 323.

(SI:DEFINE-HOST "OZ"
  ':HOST-NAMES '("OZ")
  ':MACHINE-TYPE ':UNIX
  ':SYSTEM-TYPE ':UNIX
  ':CHAOS '(#o177201))

(SI:DEFINE-HOST "LISPM-1"
  ':HOST-NAMES '("LISPM-1")
  ':MACHINE-TYPE ':CADR
  ':SYSTEM-TYPE ':LISPM
  ':CHAOS '(#o177202))

