;;; -*- Mode:LISP; Package:ZWEI; Base:8 -*-
;;; ZMail interface for Local-File
;;; All mail files are BABYL files

#+SYMBOLICS
(DEFMETHOD (FS:LM-PARSING-MIXIN :MAIL-FILE-FORMAT-COMPUTER) (IGNORE)
  'BABYL-MAIL-FILE)

#-SYMBOLICS
(DEFMETHOD (FS:LM-PARSING-MIXIN :MAIL-FILE-FORMAT-COMPUTER) (IGNORE)
  'BABYL-MAIL-FILE-BUFFER)

#+SYMBOLICS
(DEFMETHOD (FS:LM-PARSING-MIXIN :POSSIBLE-MAIL-FILE-FLAVORS) ()
  '(BABYL-MAIL-FILE))

#-SYMBOLICS
(DEFMETHOD (FS:LM-PARSING-MIXIN :POSSIBLE-MAIL-FILE-BUFFER-FLAVORS) ()
  '(BABYL-MAIL-FILE-BUFFER))

#+SYMBOLICS
(DEFMETHOD (FS:LM-PARSING-MIXIN :POSSIBLE-RMAIL-FILES) ()
  (LIST (SEND SELF :NEW-PATHNAME :NAME "BABYL" :TYPE "TEXT" :VERSION :NEWEST)))

#-SYMBOLICS
(DEFMETHOD (FS:LM-PARSING-MIXIN :POSSIBLE-MAIL-FILE-NAMES) ()
  (LIST (SEND SELF :NEW-PATHNAME :NAME "BABYL" :TYPE "TEXT" :VERSION :NEWEST)))

(DEFMETHOD (FS:LM-PARSING-MIXIN :NEW-MAIL-PATHNAME) ()
  (SEND SELF :NEW-PATHNAME :NAME "MAIL" :TYPE "TEXT" :VERSION 0))

(DEFMETHOD (FS:LM-PARSING-MIXIN :ZMAIL-TEMP-FILE-NAME) ()
  (STRING-APPEND "_ZMAIL_" (SEND SELF :TYPE)))

#+SYMBOLICS
(DEFMETHOD (FS:LM-PARSING-MIXIN :NEW-MAIL-FILE-FLAVOR) ()
  'ITS-NEW-MAIL-FILE)

#-SYMBOLICS
(DEFMETHOD (FS:LM-PARSING-MIXIN :INBOX-BUFFER-FLAVOR) ()
  'ITS-INBOX-BUFFER)
