;;; -*- Mode:LISP; Package:ZWEI; Base:8 -*-
;;; ZMail interface for Local-File
;;; All mail files are BABYL files
;;; the Symbolics versions of these methods are deleted.

(DEFMETHOD (FS:LM-PARSING-MIXIN :MAIL-FILE-FORMAT-COMPUTER) (IGNORE)
  'BABYL-MAIL-FILE-BUFFER)

(DEFMETHOD (FS:LM-PARSING-MIXIN :POSSIBLE-MAIL-FILE-BUFFER-FLAVORS) ()
  '(BABYL-MAIL-FILE-BUFFER))

(DEFMETHOD (FS:LM-PARSING-MIXIN :POSSIBLE-MAIL-FILE-NAMES) ()
  (LIST (SEND SELF :NEW-PATHNAME :NAME "BABYL" :TYPE "TEXT" :VERSION :NEWEST)))

(DEFMETHOD (FS:LM-PARSING-MIXIN :NEW-MAIL-PATHNAME) ()
  (SEND SELF :NEW-PATHNAME :NAME "MAIL" :TYPE "TEXT" :VERSION 0))

(DEFMETHOD (FS:LM-PARSING-MIXIN :ZMAIL-TEMP-FILE-NAME) ()
  (STRING-APPEND "_ZMAIL_" (SEND SELF :TYPE)))

(DEFMETHOD (FS:LM-PARSING-MIXIN :INBOX-BUFFER-FLAVOR) ()
  'ITS-INBOX-BUFFER)
