#!/usr/bin/env python3
"""Generate sys/io1/tzdata.lisp, the table of time zone names and their
POSIX TZ strings that the time code (sys/io1/time.lisp) looks a zone up in.

Source: the host's tzdata, read from /usr/share/zoneinfo (or the directory
given as the first argument).  The names are every Zone and every Link of
tzdata.zi, the compact source of the whole database (so the canonical zones
of zone1970.tab and the backward-compatible names such as US/Eastern and CET
are all there).  Each name's string is the footer of its compiled TZif file:
the POSIX TZ string on the last line of a version 2 or later file, which
tzdata writes to describe every time after the file's last transition, that
is, the zone's rule as it stands today (RFC 8536, section 3.3).  A Link's
own file may be missing, as Debian and Ubuntu move the backward-compatible
names to a separate package, so a Link takes its target zone's footer; tzdata
makes the two files the same.

The table was last generated from tzdata 2026c (tzdata.zi's "# version"
line; Ubuntu's tzdata 2026c-0ubuntu0.26.04.1), with zdump from GNU libc
2.43.  Run it again after a tzdata release and commit the table:

    python3 sys/io1/gen-tzdata.py > sys/io1/tzdata.lisp

The output is ASCII with LF line ends, spaces only.  Strings are written for
the Lisp Machine's traditional readtable, where / is the escape character,
so every / in a name or a TZ string is doubled.
"""
import os
import sys

ZONEINFO = sys.argv[1] if len(sys.argv) > 1 else '/usr/share/zoneinfo'


def footer(path):
    """The POSIX TZ string at the end of a TZif version 2+ file."""
    data = open(path, 'rb').read()
    if data[:4] != b'TZif' or data[4:5] not in (b'2', b'3', b'4'):
        raise SystemExit('%s: not a TZif version 2+ file' % path)
    lines = data.rstrip(b'\n').rsplit(b'\n', 1)
    if len(lines) != 2:
        raise SystemExit('%s: no footer' % path)
    return lines[1].decode('ascii')


def lisp_string(s):
    assert '"' not in s and '\\' not in s, s
    return '"' + s.replace('/', '//') + '"'


def main():
    version = None
    zones, links = [], []
    with open(os.path.join(ZONEINFO, 'tzdata.zi')) as f:
        for line in f:
            if line.startswith('# version '):
                version = line.split()[2]
            elif line.startswith('Z '):
                zones.append(line.split()[1])
            elif line.startswith('L '):
                target, name = line.split()[1:3]
                links.append((name, target))
    if not version:
        raise SystemExit('tzdata.zi has no version line')
    table = {z: footer(os.path.join(ZONEINFO, z)) for z in zones}
    for name, target in links:
        if target not in table:
            raise SystemExit('link %s -> %s: target is not a zone' % (name, target))
        table[name] = table[target]
    # Every name of zone1970.tab must be in the table.
    with open(os.path.join(ZONEINFO, 'zone1970.tab')) as f:
        for line in f:
            if not line.startswith('#'):
                name = line.split('\t')[2].strip()
                if name not in table:
                    raise SystemExit('zone1970.tab names %s, not in tzdata.zi' % name)

    out = sys.stdout
    out.write(';;; -*- Mode:LISP; Package:TIME; Base:10; Readtable:T -*-\n')
    out.write(';;; generated by sys/io1/gen-tzdata.py from tzdata %s: do not edit.\n' % version)
    out.write(';;; every zone and link of tzdata.zi (%d zones, %d links) with the POSIX\n'
              % (len(zones), len(links)))
    out.write(';;; TZ string its TZif file ends with, the rule the zone follows today.\n')
    out.write(';;; LOOKUP-TIMEZONE-NAME in SYS: IO1; TIME reads it.\n\n')
    out.write('(defconst *tzdata-version* %s\n' % lisp_string(version))
    out.write('  "The tzdata release that *TZDATA-ZONES* was generated from.")\n\n')
    out.write('(defconst *tzdata-zones*\n')
    out.write("  '(")
    names = sorted(table)
    for i, name in enumerate(names):
        if i:
            out.write('\n    ')
        out.write('(%s . %s)' % (lisp_string(name), lisp_string(table[name])))
    out.write(')\n')
    out.write('  "Alist of tzdata zone names and the POSIX TZ string of each.")\n')


if __name__ == '__main__':
    main()
