;;;-*-Mode:LISP; Package:UA; Base:8 -*-
;The DEFSYSTEM for CADR can cause it to be compiled/loaded in CC instead,
;but that is no problem.  As long as it is never COMPILED in USER!
;	** (c) Copyright 1980 Massachusetts Institute of Technology **
(DEFUN QUOTED-ARGS FEXPR (L) (MAPCAR (FUNCTION (LAMBDA (X) 
				(PUTPROP X '((1005 (FEF-ARG-OPT FEF-QT-QT))) 'ARGDESC))) L))

(DEFUN CLOSED FEXPR (IGNORE) NIL)
(DEFUN NOTYPE FEXPR (IGNORE) NIL)
(DEFUN FIXNUM FEXPR (IGNORE) NIL)
(DEFUN ARRAY* FEXPR (IGNORE) NIL)

(DEFUN GENPREFIX FEXPR (IGNORE) NIL)
(DEFUN EXPR-HASH FEXPR (IGNORE) NIL)

(DEFUN LIST-ASSQ (ITEM IN-LIST)
  (PROG ()
     L	(COND ((NULL IN-LIST) (RETURN NIL))
	      ((EQ ITEM (CAR IN-LIST))
		(RETURN (CADR IN-LIST))))
	(SETQ IN-LIST (CDDR IN-LIST))
	(GO L)))

(DECLARE (SPECIAL **INDICATOR**))
(DEFUN ALLREMPROP (**INDICATOR**)
 (MAPATOMS (FUNCTION (LAMBDA (X) (REMPROP X **INDICATOR**)))))

(DEFUN INCLUDE (&QUOTE &REST IGNORE))
