(SI#:DEFINE-SIMPLE-TRANSFORMATION :MICRO-ASSEMBLE UA#:MICRO-ASSEMBLE-SYSTEM-TOP-LEVEL
     UA#:FILE-TEST-ALWAYS ((IF (FDEFINEDP 'FS#:DEFINE-CANONICAL-TYPE) ':LISP "LISP")) ("MCR")
     NIL NIL T)	;LOAD like

(SI#:DEFINE-MAKE-SYSTEM-SPECIAL-VARIABLE SI#:*FILES-TO-MICRO-ASSEMBLE* NIL)

(DEFSYSTEM UCODE
    (:NAME "Ucode")
    (:PACKAGE "UA")
    (:OUTPUT-PATHNAME "SYS:UBIN;UCADR")
    (:COMPONENT-SYSTEMS UA)
    (:PATHNAME-DEFAULT "SYS:UCADR;")
    (:USE-FAST-READER T)
    (:DO-COMPONENTS ())
    (:MICRO-ASSEMBLE ("UC-PARAMETERS" "UC-CADR"  ;UC-CADR must follow UC-PARAMETERS
		      "UC-MACROCODE" "UC-CALL-RETURN" "UC-STORAGE-ALLOCATION"
		      "UC-FCTNS" "UC-ARRAY" "UC-LOGICAL" 
		      "UC-ARITH" "UC-STRING" "UC-TRANSPORTER"
		      "UC-STACK-CLOSURE"
		      "UC-METER" "UC-HACKS" "UC-TV" "UC-TRACK-MOUSE"
		      "UC-PAGE-FAULT" "UC-DISK" "UC-INTERRUPT" 
		      "UC-CHAOS" "UC-STACK-GROUPS" "UC-COLD-DISK" "UC-MC"
;		      "UC-PUP"
		      )))